// utils/linkedWalletSync.ts
//
// Keeps a wallet transaction's editable fields (description, amount, date)
// in sync with whatever parent record it's linked to (a Contribution, an
// Investment's disbursement, or a Loan's disbursement).
//
// WHY THIS EXISTS:
//
//   wallet.tsx / edit-transaction.tsx already let you edit a wallet tx
//   directly, and every screen that shows financial data (contributions.tsx,
//   loans.tsx, investments.tsx, wallet.tsx) reads from the SAME Zustand
//   slice (`walletTransactions`). So editing a wallet tx already propagates
//   everywhere for free — there was never a second copy of the data.
//
//   What was missing is the OTHER direction: editing a Contribution, Loan,
//   or Investment's amount/date did not touch its linked wallet
//   transaction, so the wallet screen would silently show stale numbers.
//
//   This helper is called from each domain slice's update action, AFTER
//   the parent record's own Firestore write succeeds, to patch the one
//   linked wallet tx to match.
//
// SCOPE (per explicit decision — see conversation):
//   - Only description / amount / date are synced this way.
//   - Loan due-date rescheduling is handled separately (see
//     rescheduleLoanInstallment in loanSlice.ts) because schedule items
//     don't have wallet transactions until a repayment actually happens —
//     there's nothing to sync until then.
//   - This does NOT change tx.type, sourceType, or any cascade/relation
//     field. Those stay under the wallet slice's own editing rules
//     (see MANUAL_TYPES in edit-transaction.tsx — only standalone/manual
//     transactions may have their type reassigned).
//
// ASSUMPTIONS — please verify against your actual codebase:
//   1. A Contribution's linked wallet tx is found via `contributionId`
//      (matches how contributionSlice.ts and lateFees.ts already look
//      these up). If a contribution can have MORE than one linked tx
//      (e.g. late fees also stamped with the same contributionId), this
//      only touches txs with `type === "contribution"` to avoid
//      clobbering a late-fee row — adjust the type filter if your data
//      shapes this differently.
//   2. An Investment's linked wallet tx is found via `investmentId` and
//      `type === "investment_disbursement"`. I don't have
//      investmentSlice.ts, so this assumes `createInvestment`/
//      `disburseInvestment`-equivalent code stamps investmentId the same
//      way loanSlice stamps loanId — verify the field name matches.
//   3. A Loan's DISBURSEMENT wallet tx is found via `loanId` and
//      `type === "loan_disbursement"`. Repayment txs (interest/principal)
//      are intentionally NOT touched here — those are generated by
//      FS.recordRepaymentServer from the repayment amount itself, so
//      "editing the loan" has no single obvious repayment tx to target.
//      If you need to correct a specific repayment, that's still an
//      edit-transaction.tsx job (edit the wallet tx directly).

import type { WalletTransaction } from "../types";

export interface LinkedSyncPatch {
  description?: string;
  amount?: number;
  date?: string;
}

/**
 * Finds the wallet transaction linked to a contribution.
 */
export function findContributionWalletTx(
  walletTransactions: WalletTransaction[],
  contributionId: string,
): WalletTransaction | undefined {
  return walletTransactions.find(
    (t) =>
      t.contributionId === contributionId &&
      t.type === "contribution",
  );
}

/**
 * Finds the wallet transaction linked to an investment's disbursement.
 */
export function findInvestmentWalletTx(
  walletTransactions: WalletTransaction[],
  investmentId: string,
): WalletTransaction | undefined {
  return walletTransactions.find(
    (t) =>
      t.investmentId === investmentId &&
      t.type === "investment_disbursement",
  );
}

/**
 * Finds the wallet transaction linked to a loan's disbursement.
 * (Repayment txs are not covered — see ASSUMPTION 3 above.)
 */
export function findLoanDisbursementWalletTx(
  walletTransactions: WalletTransaction[],
  loanId: string,
): WalletTransaction | undefined {
  return walletTransactions.find(
    (t) =>
      t.loanId === loanId &&
      t.type === "loan_disbursement",
  );
}

/**
 * Builds the patch to apply to a linked wallet tx, given the fields that
 * changed on its parent record. Preserves the tx's existing sign
 * (credit/debit) — only the magnitude changes, exactly like
 * edit-transaction.tsx does for direct wallet edits.
 */
export function buildLinkedTxPatch(
  existingTx: WalletTransaction,
  changed: LinkedSyncPatch,
): Partial<WalletTransaction> {
  const patch: Partial<WalletTransaction> = {};

  if (changed.description !== undefined) {
    patch.description = changed.description;
  }

  if (changed.date !== undefined) {
    patch.date = changed.date;
  }

  if (changed.amount !== undefined) {
    const wasCredit = (existingTx.amount ?? 0) >= 0;
    patch.amount = wasCredit
      ? Math.abs(changed.amount)
      : -Math.abs(changed.amount);
  }

  return patch;
}